# Generated by Django 5.0.4 on 2024-05-13 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginsignin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
