# Generated by Django 5.0.4 on 2024-05-21 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginsignin', '0004_custommodelname'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date_task',
            field=models.DateTimeField(null=True),
        ),
    ]
