# Generated by Django 5.0.4 on 2024-05-22 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginsignin', '0006_remove_task_date_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date_task',
            field=models.DateTimeField(null=True),
        ),
    ]
