# Generated by Django 5.0.4 on 2024-05-22 13:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginsignin', '0009_alter_task_date_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_task',
            field=models.DateField(default=datetime.date, null=True),
        ),
    ]
