# Generated by Django 5.0.4 on 2024-05-22 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginsignin', '0010_alter_task_date_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='date_task',
        ),
    ]
